name: router-mesh
resolver:
  host: 127.0.0.11
  ttl: 3s
root: /app/web
router_mesh_port: 83
services:
  backend:
    protocol: https
    service_name: backend_service
    server: backend
    port: 443
    expose_external: true
    healthcheck: true
    healthcheck_uri: /
  web:
    protocol: https
    service_name: web_service
    server: web
    port: 443
    expose_external: true
    healthcheck: true
    healthcheck_uri: /
streams: